# Generated by Django 4.1.5 on 2023-03-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_info', models.JSONField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('paid', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaidContent',
            fields=[
                ('paid_content', models.BigIntegerField(primary_key=True, serialize=False)),
                ('content_name', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('content_HTML', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'paid_Ncontent',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, null=True)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_address', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=16)),
                ('usd_amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pay_amount', models.DecimalField(decimal_places=8, max_digits=16)),
                ('paid', models.BooleanField(default=False)),
                ('payment_id', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chanel_control.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chanel_control.users')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chanel_control.users'),
        ),
    ]
