# Generated by Django 4.1.5 on 2023-03-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanel_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidcontent',
            name='content_HTML',
            field=models.CharField(max_length=2047, null=True),
        ),
    ]
