# Generated by Django 4.1.5 on 2023-03-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chanel_control', '0002_alter_paidcontent_content_html'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paidcontent',
            table='paid_content',
        ),
    ]
